# https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#repositories
# ArgoCD 배포 이후 웹UI를 통하지않고, 터미널에서 레포연동 설정을 위해 실행
# 로컬 실행시 ghp_BOT_TOKEN을 수정하여 사용

apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: Secret
metadata:
  name: sync-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/nasir17git/logonme
  # username: nasir17git
  # password: ghp_BOT_TOKEN
