apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: addons
  namespace: argocd
spec:
  description: argo-addons-project
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    name: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  description: k8s-apps-project
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    name: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
