# helm repo add metallb https://metallb.github.io/metallb
# helm upgrade metallb metallb/metallb -n kube-system --version 0.13.12 -f deploy/addons/base/network/metallb/metallb-values.yaml -i
# https://artifacthub.io/packages/helm/metallb/metallb/0.13.12

controller:
  affinity: 
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - nasir-k8s-control-plane
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule