# helm repo add opentelemetry-helm https://open-telemetry.github.io/opentelemetry-helm-charts
# helm upgrade operator-otel opentelemetry-helm/opentelemetry-operator --version 0.55.3 -n monitoring -f deploy/addons/base/observability/otel/operator.yaml -i
# https://artifacthub.io/packages/helm/opentelemetry-helm/opentelemetry-operator/0.55.3 


# https://nangman14.tistory.com/m/111
admissionWebhooks:
  certManager:
    enabled: false
  autoGenerateCert:
    enabled: true