
name: tool-cache
run-name: "build tool-cached runner, v.${{ inputs.BASE_IMAGE_VERSION }}"

on:
  workflow_dispatch:
    inputs:
      BUILD_MACHINE:
        description: '빌드를 진행할 머신을 선택해주세요(택1)'
        type: string
        # type: choice
        # options:
        #   - k8s-runner
        #   - ubuntu-latest
      BASE_IMAGE_VERSION:
        description: ghcr.io/actions/actions-runner의 버전 입력. 기본값 latest
        type: string
        default: latest
      DEBUG:
        description: 'debug 세션 활성화'
        type: boolean
        required: false

jobs:
  create-tool-cache:
    runs-on: ${{ inputs.BUILD_MACHINE }}
    steps:
      - name: Clear any existing tool cache
        run: |
          mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
          mkdir -p "${{ runner.tool_cache }}"          

      - name: Setup python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13' 
      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Archive tool cache
        working-directory: ${{ runner.tool_cache }}
        run: |
          tar -czf tool_cache.tar.gz *   

      - name: Upload tool cache artifact
        uses: actions/upload-artifact@v4
        with:
          name: tools
          retention-days: 1
          path: ${{runner.tool_cache}}/tool_cache.tar.gz

  build-with-tool-cache:
    runs-on:  ${{ inputs.BUILD_MACHINE }}
    needs: create-tool-cache
    env:
      # Setup some variables for naming the image automatically
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: checkout src
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: tools
          path: ${{github.workspace}}/tools

      - name: Unpack tools
        run: |
          tar -xzf ${{github.workspace}}/tools/tool_cache.tar.gz -C ${{github.workspace}}/tools/
          rm ${{github.workspace}}/tools/tool_cache.tar.gz          

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build & push
        run: |
          sed -i 's/__BASE_IMAGE_VERSION__/${{ inputs.BASE_IMAGE_VERSION }}/g' tool-cache
          docker build . -f tool-cache -t nasir17/gha-demo:latest
        
      - name: make debug-session
        if: ${{ failure() || inputs.debug == 'true' }}
        run: |
          screen -dmS debug bash
          echo "Debug session started. To end normally, create /tmp/end_debug file."
          echo "Runner name: ${{ runner.name }}"
          echo "To connect: screen -r debug"
          echo "To end : touch /tmp/end_debug"
          while [ ! -f /tmp/end_debug ]; do sleep 10; done
          echo "Debug session ended normally."
